#!/bin/sh

source "lib/main.sh"

echo $STARTED_TEXT

for f in templates/*; do
  # basename command to extract the filename from the path
  fname=`basename $f`

  echo "$undgrn $fname $txtrst -- $bldpur ok. $txtrst"

  # touch file
  touch_template $fname
done

echo $END_TEXT

# Source setup profile file.
source $HOME/.profile
